export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const OPEN_POPUP_WINDOW = 'OPEN_POPUP_WINDOW';
export const CLOSE_POPUP_WINDOW = 'CLOSE_POPUP_WINDOW';


export const CREATE_PROJECT_CARD = 'CREATE_PROJECT_CARD';
export const EDIT_PROJECT_CARD = 'EDIT_PROJECT_CARD';
