export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';


export const OPEN_POPUP_WINDOW = 'OPEN_POPUP_WINDOW';
export const CLOSE_POPUP_WINDOW = 'CLOSE_POPUP_WINDOW';


export const CREATE_PROJECT_CARD = 'CREATE_PROJECT_CARD';
export const EDIT_PROJECT_CARD = 'EDIT_PROJECT_CARD';
export const REMOVE_PROJECT_CARD = 'REMOVE_PROJECT_CARD';
export const MOVE_PROJECT_CARD = 'MOVE_PROJECT_CARD';
export const UNDO_CARDS = 'UNDO_CARDS';
export const REDO_CARDS = 'REDO_CARDS';
export const GET_REMOTE_CARDS = 'GET_REMOTE_CARDS';


export const GET_CURRENT_PROJECT_DATA = 'GET_CURRENT_PROJECT_DATA';
export const GET_REMOTE_PROJECT_DATA = 'GET_REMOTE_PROJECT_DATA';
export const UNDO_CURRENT_PROJECT = 'UNDO_CURRENT_PROJECT';
export const REDO_CURRENT_PROJECT = 'REDO_CURRENT_PROJECT';


export const OPEN_WS = 'OPEN_WS';
export const CLOSE_WS = 'CLOSE_WS';