export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const CHANGE_CARDS = 'CHANGE_CARDS';
export const OPEN_PROJECT = 'OPEN_PROJECT';
export const CHANGE_PROJECT = 'CHANGE_PROJECT';
export const CLOSE_PROJECT = 'CLOSE_PROJECT';